remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: elkninja chronicles
description: putting the query in inquiry

show_downloads: true
google_analytics: "G-7SVPT506B1"
